<?php
    namespace frontend\models;

    use common\models\House;
    use common\models\Realty;
    use yii\base\Model;
    use yii\db\Query;

    class HouseModel extends Model{
        public $districtId;
        public $serviceType;
        public $price;
        public $houseArea;
        public $distance;

        public $priceInterval;
        public $areaInterval;
        public $distanceInterval;

        public function rules(){
            return [
                [['districtId', 'realtyType', 'serviceType'], 'integer'],
                [['price', 'houseArea', 'distance'], 'string'],
            ];
        }

        public function init(){
            $query = new Query();
            $price = $query->select('price')->from(Realty::tableName())->where(['realty_type_id'=>1]);
            $minPrice = $price->min('price');
            $maxPrice = $price->max('price');
            $query = new Query();
            $area = $query->select('house_area')->from(House::tableName());
            $minArea = $area->min('house_area');
            $maxArea = $area->max('house_area');
            $query = new Query();
            $distance = $query->select('distance')->from(House::tableName());
            $minDistance = $distance->min('distance');
            $maxDistance = $distance->max('distance');

            $this->priceInterval = ['min'=>$minPrice, 'max'=>$maxPrice];
            $this->distanceInterval = ['min'=>$minDistance, 'max'=>$maxDistance];
            $this->areaInterval = ['min'=>$minArea, 'max'=>$maxArea];

            parent::init(); // TODO: Change the autogenerated stub
        }
    }